### ISSUE TITLE
Breaks server

### ISSUE THREAD

**Issue by Amanedan** [mrmicheall/esx_traphouse#1]
it seems that whenever i have the script start nobody can connect except me. and when i connect it spawns me in as franklin. it might a completly unrelated issue but it only happens when i have this script started. i really love this script but it dosnt seem to love me or my server back lmao. any idea's how to fix???

**Comment by mrmicheall** [comment]
You see any errors in the console or anything? Works fine on the servers I have put it on. It's a modified esx_holdup script, you could try that and see if that causes the same thing. But tbh, without seeing any errors in console or from the F8, it's hard to troubleshoot anything.
